// <auto-generated />
namespace YouOpine2.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Addcolumforvalidationuser : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addcolumforvalidationuser));
        
        string IMigrationMetadata.Id
        {
            get { return "202012030247228_Add colum for validation user"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
